# Generated by Django 3.2.7 on 2021-09-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='Имя')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('about', models.TextField(verbose_name=' О нём')),
            ],
        ),
    ]
