# Generated by Django 3.2.7 on 2021-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
