# Generated by Django 3.2.7 on 2021-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_brain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('dev', models.CharField(max_length=255, verbose_name='Разработчики игры')),
                ('rel', models.CharField(max_length=255, verbose_name='Дата редиза')),
                ('ser', models.IntegerField(verbose_name='Версия игры')),
                ('gen', models.CharField(max_length=255, verbose_name='Жанр игры')),
            ],
        ),
    ]
